Updated custom scripts

diff --git a/bin/media-info b/bin/media-info
--- a/bin/media-info
+++ b/bin/media-info
@@ -1,93 +1,75 @@
 #!/bin/sh
+##################################################################
+# Get media information about audio/video files
 #
-# Get media information about audio/video files.
+# Michael Pratt
+# http://www.michael-pratt.com
+#
+# License: MIT
+# Copyright (C) 2017 by Michael Pratt
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice shall be included in
+# all copies or substantial portions of the Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
+# THE SOFTWARE.
+##################################################################
+set -e
+
+gui=0
+f=""
 
 usage() {
-    echo "$0 -f <filename> [-c] [-w width(int)] [-h height(int)] [-t window-title]"
-    echo
-    echo " required:"
-    echo "   -f    input filename"
-    echo
-    echo " optional:"
-    echo "   -c    no-gui, show console output (zenity not required)"
-    echo "         default is to show gui"
-    echo
-    echo "   -w    (gui) width of window (e.g.: -w 800)"
-    echo "         default is 800"
-    echo
-    echo "   -h    (gui) height of window (e.g.: -h 240)"
-    echo "         default is 240"
-    echo
-    echo "   -t    (gui) window title"
-    echo "         default is filename"
-    echo
-    exit 1
+    echo "$(basename ${0}) -f <file> [-g]"
+    echo "  -f   input filename"
+    echo "  -g   show results in zenity gui"
+    echo ""
 }
 
+if [ "${#}" -eq 0 ]; then
+    usage
+    exit 0
+fi
 
-while getopts ":f:cw:h:t:" i; do
+while getopts ":f:g" i; do
     case "${i}" in
-        f)
-            f=${OPTARG}
-            ;;
-        c)
-            c=yes
-            ;;
-        w)
-            w=${OPTARG}
-            ;;
-        h)
-            h=${OPTARG}
-            ;;
-        t)
-            t=${OPTARG}
-            ;;
+        f) f=${OPTARG} ;;
+        g) gui=1 ;;
         *)
             echo "Error - unrecognized option $1" 1>&2;
             usage
+            exit 1
             ;;
     esac
 done
 shift $((OPTIND-1))
 
-# Check if file is specified
-if [ -z "${f}" ]; then
-    echo "Error - no file specified" 1>&2;
+if ! [ -e  "${f}" ] || [ -z "${f}" ]; then
+    echo "File not found ${f}"
     usage
-fi
-
-# Check if zenity exists
-if ! command -v zenity >/dev/null 2>&1 ; then
-    echo "Error - 'zenity' not found." 1>&2
     exit 1
 fi
 
-# Check if zenity exists
-if ! command -v ffmpeg >/dev/null 2>&1 ; then
-    echo "Error - 'ffmpeg' not found." 1>&2
-    exit 1
-fi
-
-
-########################## console output ###############################
+OUTPUT=$(ffmpeg -i "${f}"  2>&1 | grep -e Stream -e Duration -e Input -e title -e artist -e genre -e comment -e album -e date)
 
 # Do we have textbased output?
-if [ -n "${c}" ]; then
-    ffmpeg -i "${f}"  2>&1 \
-        | grep -e Stream -e Duration -e Input
-    exit 0
+if [ "${gui}" -eq 1 ]; then
+    WIDTH=600
+    HEIGHT=350
+    TITLE="Media Info for: $(basename "${f}")"
+    echo -e "${OUTPUT}" | zenity --width=${WIDTH} --height=${HEIGHT} --text-info --title "${TITLE}"
+else
+    echo -e "${OUTPUT}"
 fi
-
-
-########################## gui output ###############################
-[ ! -z "${w##*[!0-9]*}" ]	&& WIDTH=$f		|| WIDTH=800
-[ ! -z "${h##*[!0-9]*}" ]	&& HEIGHT=$f	|| HEIGHT=240
-[ -n "${t}" ]				&& TITLE=$t		|| TITLE="Media Info for: $(basename "${f}")"
-
-
-
-ffmpeg -i "${f}"  2>&1 \
-    | grep -e Stream -e Duration -e Input \
-    | zenity --width=${WIDTH} --height=${HEIGHT} --text-info --title "${TITLE}"
-
-exit 0
